In [1]:
import pandas as pd

## 1- Carregando dados

In [ ]:
df_raw = pd.read_csv('DADOS\MICRODADOS_ENEM_2023.csv', encoding='latin-1', sep=';')
df_raw

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\Rafael Luckner\AppData\Local\Temp\ipykernel_13876\2779417389.py:1: SyntaxWarning: invalid escape sequence '\M'
  df_raw = pd.read_csv('DADOS\MICRODADOS_ENEM_2023.csv', encoding='latin-1', sep=';')

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210059085136,2023,14,M,2,1,1,1,17,1,...,C,C,B,B,A,B,B,A,A,B
1,210059527735,2023,12,M,2,1,0,1,16,1,...,B,A,B,B,A,A,C,A,D,B
2,210061103945,2023,6,F,1,1,1,1,0,1,...,B,A,A,B,A,A,A,A,A,B
3,210060214087,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3933950,210061959676,2023,12,M,1,1,1,1,6,1,...,B,A,A,C,A,B,E,A,A,B
3933951,210061950911,2023,1,F,1,1,2,3,0,1,...,B,A,B,C,B,B,B,B,C,B
3933952,210061965966,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
3933953,210061932304,2023,2,M,1,1,1,2,0,3,...,B,B,B,C,A,A,D,A,C,B
3933954,210058924455,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,B,A,D,A,B,B

## 2- Filtrando colunas necessárias

In [ ]:
df_raw.columns

Index(['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO',
       'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO',
       'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO',
       'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC',
       'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA',
       'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC',
       'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT',
       'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC',
       'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH',
       'TX_GABARITO_LC', 'TX_GABARITO_MT', 'TP_STATUS_REDACAO',
       'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4',
       'NU_NOTA_COMP5', 'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004',
       'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013',
       'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022',
       'Q023', 'Q024', 'Q025'],
      dtype='object')

In [ ]:
df_colunas_filtradas = df_raw[['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO',
            'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO',
            'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO',
            'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC',
            'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC',
            'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA','SG_UF_PROVA',
            'TP_PRESENCA_CN','TP_PRESENCA_CH','TP_PRESENCA_LC', 'TP_PRESENCA_MT',
            'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT','NU_NOTA_REDACAO',
            'Q001', 'Q002', 'Q003', 'Q004','Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013',
            'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022','Q023', 'Q024', 'Q025']].copy()
df_colunas_filtradas

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210059085136,2023,14,M,2,1,1,1,17,1,...,C,C,B,B,A,B,B,A,A,B
1,210059527735,2023,12,M,2,1,0,1,16,1,...,B,A,B,B,A,A,C,A,D,B
2,210061103945,2023,6,F,1,1,1,1,0,1,...,B,A,A,B,A,A,A,A,A,B
3,210060214087,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3933950,210061959676,2023,12,M,1,1,1,1,6,1,...,B,A,A,C,A,B,E,A,A,B
3933951,210061950911,2023,1,F,1,1,2,3,0,1,...,B,A,B,C,B,B,B,B,C,B
3933952,210061965966,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
3933953,210061932304,2023,2,M,1,1,1,2,0,3,...,B,B,B,C,A,A,D,A,C,B
3933954,210058924455,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,B,A,D,A,B,B

## 3- Filtrando linhas necessárias

In [ ]:
df_ceara = df_colunas_filtradas.loc[df_colunas_filtradas['SG_UF_ESC'] == 'CE'].copy()
df_ceara

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
3,210060214087,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,A
48,210059388092,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
79,210060373830,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
124,210059246975,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,B,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3927179,210058871875,2023,12,M,1,3,1,2,0,2,...,A,A,A,A,A,A,A,A,A,A
3930225,210059873720,2023,13,M,1,3,1,2,0,2,...,A,A,A,A,A,A,A,A,A,A
3931066,210059019411,2023,9,F,1,2,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
3931809,210061699604,2023,17,F,1,3,1,2,0,2,...,B,A,A,A,A,A,A,A,A,A
3933541,210060852754,2023,3,M,1,3,4,2,0,2,...,A,A,A,B,A,A,E,B,A,B

## 4- Mapeando colunas

In [ ]:
df_ceara['TP_DEPENDENCIA_ADM_ESC'] = df_ceara['TP_DEPENDENCIA_ADM_ESC'].astype('int64')
df_ceara['TP_DEPENDENCIA_ADM_ESC'] = df_ceara['TP_DEPENDENCIA_ADM_ESC'].map({1: 'Federal', 2: 'Estadual', 3: 'Municipal', 4: 'Privada'})

df_ceara['TP_DEPENDENCIA_ADM_ESC'].unique()

array(['Estadual', 'Federal', 'Privada', 'Municipal'], dtype=object)

In [ ]:
df_ceara['TP_LOCALIZACAO_ESC'] = df_ceara['TP_LOCALIZACAO_ESC'].astype('int64')
df_ceara['TP_LOCALIZACAO_ESC'] = df_ceara['TP_LOCALIZACAO_ESC'].map({1: 'Urbana', 2: 'Rural'})

df_ceara['TP_LOCALIZACAO_ESC'].unique()

array(['Urbana', 'Rural'], dtype=object)

In [ ]:
colunas = ['TP_PRESENCA_CN','TP_PRESENCA_CH', 'TP_PRESENCA_LC','TP_PRESENCA_MT']

df_ceara[colunas] = df_ceara[colunas].apply(lambda celula: celula.map({0 : 'Faltou', 1 : 'Presente', 2: 'Eliminado'} ) if celula.dtype == 'int64' else celula  )
df_ceara[colunas]

        TP_PRESENCA_CN TP_PRESENCA_CH TP_PRESENCA_LC TP_PRESENCA_MT
3             Presente       Presente       Presente       Presente
4             Presente       Presente       Presente       Presente
48            Presente       Presente       Presente       Presente
79            Presente       Presente       Presente       Presente
124             Faltou         Faltou         Faltou         Faltou
...                ...            ...            ...            ...
3927179         Faltou         Faltou         Faltou         Faltou
3930225         Faltou         Faltou         Faltou         Faltou
3931066         Faltou         Faltou         Faltou         Faltou
3931809         Faltou         Faltou         Faltou         Faltou
3933541       Presente       Presente       Presente       Presente

[98595 rows x 4 columns]

In [ ]:
df_filter_final = df_ceara[(df_ceara['TP_PRESENCA_CN'] == "Presente") & (df_ceara['TP_PRESENCA_CH'] == "Presente") & (df_ceara['TP_PRESENCA_LC'] == "Presente")& (df_ceara['TP_PRESENCA_MT'] == "Presente")].copy()
df_filter_final

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
3,210060214087,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,A
48,210059388092,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
79,210060373830,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
165,210060440974,2023,4,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3908024,210061008506,2023,4,M,1,3,1,2,0,2,...,A,A,A,C,A,A,D,A,B,B
3918192,210060298399,2023,2,M,1,1,1,2,0,3,...,B,A,B,C,B,B,E,A,E,B
3923578,210061481447,2023,11,M,2,3,1,2,0,2,...,A,A,A,A,A,A,A,A,A,A
3925210,210059173679,2023,9,F,1,1,1,2,0,2,...,A,A,A,C,A,A,E,B,B,B
3933541,210060852754,2023,3,M,1,3,4,2,0,2,...,A,A,A,B,A,A,E,B,A,B

In [ ]:
df_filter_final.drop(['TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT'], axis=1, inplace=True)
df_filter_final

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
3,210060214087,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,A
48,210059388092,2023,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
79,210060373830,2023,2,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
165,210060440974,2023,4,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3908024,210061008506,2023,4,M,1,3,1,2,0,2,...,A,A,A,C,A,A,D,A,B,B
3918192,210060298399,2023,2,M,1,1,1,2,0,3,...,B,A,B,C,B,B,E,A,E,B
3923578,210061481447,2023,11,M,2,3,1,2,0,2,...,A,A,A,A,A,A,A,A,A,A
3925210,210059173679,2023,9,F,1,1,1,2,0,2,...,A,A,A,C,A,A,E,B,B,B
3933541,210060852754,2023,3,M,1,3,4,2,0,2,...,A,A,A,B,A,A,E,B,A,B

# Mapeamento dados socioeconômicos

In [ ]:
# Mapeamento de TP_FAIXA_ETARIA
df_filter_final['TP_FAIXA_ETARIA'] = df_filter_final['TP_FAIXA_ETARIA'].replace({
    1: 'Menor de 17 anos', 2: '17 anos', 3: '18 anos', 4: '19 anos', 5: '20 anos',
    6: '21 anos', 7: '22 anos', 8: '23 anos', 9: '24 anos', 10: '25 anos',
    11: 'Entre 26 e 30 anos', 12: 'Entre 31 e 35 anos', 13: 'Entre 36 e 40 anos',
    14: 'Entre 41 e 45 anos', 15: 'Entre 46 e 50 anos', 16: 'Entre 51 e 55 anos',
    17: 'Entre 56 e 60 anos', 18: 'Entre 61 e 65 anos', 19: 'Entre 66 e 70 anos',
    20: 'Maior de 70 anos'
})
df_filter_final['TP_FAIXA_ETARIA']

3                     17 anos
4                     18 anos
48                    18 anos
79                    17 anos
165                   19 anos
                  ...
3908024               19 anos
3918192               17 anos
3923578    Entre 26 e 30 anos
3925210               24 anos
3933541               18 anos
Name: TP_FAIXA_ETARIA, Length: 74319, dtype: object

In [ ]:
# TP_ESTADO_CIVIL
df_filter_final['TP_ESTADO_CIVIL'] = df_filter_final['TP_ESTADO_CIVIL'].replace({
    0: 'Não informado', 1: 'Solteiro(a)', 2: 'Casado(a)/Mora com companheiro(a)',
    3: 'Divorciado(a)/Desquitado(a)/Separado(a)', 4: 'Viúvo(a)'
})

In [ ]:
# TP_COR_RACA
df_filter_final['TP_COR_RACA'] = df_filter_final['TP_COR_RACA'].astype('int64').replace({
    0: 'Não declarado', 1: 'Branca', 2: 'Preta', 3: 'Parda', 4: 'Amarela', 5: 'Indígena', 6: 'Não dispõe da informação'
})
df_filter_final['TP_COR_RACA']

3           Parda
4           Parda
48          Parda
79          Parda
165         Parda
            ...
3908024     Parda
3918192    Branca
3923578     Parda
3925210    Branca
3933541     Parda
Name: TP_COR_RACA, Length: 74319, dtype: object

In [ ]:
# TP_NACIONALIDADE
df_filter_final['TP_NACIONALIDADE'] = df_filter_final['TP_NACIONALIDADE'].astype('int64').replace({
    0: 'Não informado', 1: 'Brasileiro(a)', 2: 'Brasileiro(a) Naturalizado(a)',
    3: 'Estrangeiro(a)', 4: 'Brasileiro(a) Nato(a), nascido(a) no exterior'
})
df_filter_final['TP_NACIONALIDADE']

3                                          Brasileiro(a)
4                                          Brasileiro(a)
48                                         Brasileiro(a)
79                                         Brasileiro(a)
165                                        Brasileiro(a)
                               ...
3908024                                    Brasileiro(a)
3918192                                    Brasileiro(a)
3923578                                    Brasileiro(a)
3925210                                    Brasileiro(a)
3933541    Brasileiro(a) Nato(a), nascido(a) no exterior
Name: TP_NACIONALIDADE, Length: 74319, dtype: object

In [ ]:
# TP_ST_CONCLUSAO
df_filter_final['TP_ST_CONCLUSAO'] = df_filter_final['TP_ST_CONCLUSAO'].astype('int64').replace({
    1: 'Já concluí o Ensino Médio', 2: 'Estou cursando e concluirei em 2023',
    3: 'Estou cursando e concluirei após 2023', 4: 'Não concluí e não estou cursando'
})
df_filter_final['TP_ST_CONCLUSAO']

3          Estou cursando e concluirei em 2023
4          Estou cursando e concluirei em 2023
48         Estou cursando e concluirei em 2023
79         Estou cursando e concluirei em 2023
165        Estou cursando e concluirei em 2023
                          ...
3908024    Estou cursando e concluirei em 2023
3918192    Estou cursando e concluirei em 2023
3923578    Estou cursando e concluirei em 2023
3925210    Estou cursando e concluirei em 2023
3933541    Estou cursando e concluirei em 2023
Name: TP_ST_CONCLUSAO, Length: 74319, dtype: object

In [ ]:
# TP_ANO_CONCLUIU
df_filter_final['TP_ANO_CONCLUIU'] = df_filter_final['TP_ANO_CONCLUIU'].astype('int64').replace({
    0: 'Não informado', 1: '2022', 2: '2021', 3: '2020', 4: '2019', 5: '2018',
    6: '2017', 7: '2016', 8: '2015', 9: '2014', 10: '2013', 11: '2012',
    12: '2011', 13: '2010', 14: '2009', 15: '2008', 16: '2007', 17: 'Antes de 2007'
})
df_filter_final['TP_ANO_CONCLUIU']

3          Não informado
4          Não informado
48         Não informado
79         Não informado
165        Não informado
               ...
3908024    Não informado
3918192    Não informado
3923578    Não informado
3925210    Não informado
3933541    Não informado
Name: TP_ANO_CONCLUIU, Length: 74319, dtype: object

In [ ]:
# TP_ESCOLA
df_filter_final['TP_ESCOLA'] = df_filter_final['TP_ESCOLA'].astype('int64').replace({
    1: 'Não Respondeu', 2: 'Pública', 3: 'Privada'
})
df_filter_final['TP_ESCOLA']

3          Pública
4          Pública
48         Pública
79         Pública
165        Pública
            ...
3908024    Pública
3918192    Privada
3923578    Pública
3925210    Pública
3933541    Pública
Name: TP_ESCOLA, Length: 74319, dtype: object

In [ ]:
# TP_ENSINO
df_filter_final['TP_ENSINO'] = df_filter_final['TP_ENSINO'].replace({
    1: 'Ensino Regular', 2: 'Educação Especial - Modalidade Substitutiva'
})
df_filter_final['TP_ENSINO']

3          Ensino Regular
4          Ensino Regular
48         Ensino Regular
79         Ensino Regular
165        Ensino Regular
                ...
3908024    Ensino Regular
3918192    Ensino Regular
3923578               NaN
3925210               NaN
3933541    Ensino Regular
Name: TP_ENSINO, Length: 74319, dtype: object

In [ ]:
# IN_TREINEIRO
df_filter_final['IN_TREINEIRO'] = df_filter_final['IN_TREINEIRO'].astype('int64').replace({
    0: 'Não', 1: 'Sim'
})
df_filter_final['IN_TREINEIRO']

3          Não
4          Não
48         Não
79         Não
165        Não
          ...
3908024    Não
3918192    Não
3923578    Não
3925210    Não
3933541    Não
Name: IN_TREINEIRO, Length: 74319, dtype: object

In [ ]:
# TP_SIT_FUNC_ESC
df_filter_final['TP_SIT_FUNC_ESC'] = df_filter_final['TP_SIT_FUNC_ESC'].replace({
    1: 'Em atividade', 2: 'Paralisada', 3: 'Extinta', 4: 'Extinta em anos anteriores'
})
df_filter_final['TP_SIT_FUNC_ESC']

3          Em atividade
4          Em atividade
48         Em atividade
79         Em atividade
165        Em atividade
               ...
3908024    Em atividade
3918192    Em atividade
3923578    Em atividade
3925210    Em atividade
3933541    Em atividade
Name: TP_SIT_FUNC_ESC, Length: 74319, dtype: object

In [ ]:
# TP_DEPENDENCIA_ADM_ESC
df_filter_final['TP_DEPENDENCIA_ADM_ESC'] = df_filter_final['TP_DEPENDENCIA_ADM_ESC'].replace({
    1: 'Federal', 2: 'Estadual', 3: 'Municipal', 4: 'Privada'
})
df_filter_final['TP_DEPENDENCIA_ADM_ESC']

3          Estadual
4          Estadual
48         Estadual
79         Estadual
165        Estadual
             ...
3908024     Federal
3918192     Privada
3923578    Estadual
3925210    Estadual
3933541     Federal
Name: TP_DEPENDENCIA_ADM_ESC, Length: 74319, dtype: object

In [ ]:
# TP_LOCALIZACAO_ESC
df_filter_final['TP_LOCALIZACAO_ESC'] = df_filter_final['TP_LOCALIZACAO_ESC'].replace({
    1: 'Urbana', 2: 'Rural'
})
df_filter_final['TP_LOCALIZACAO_ESC']

3          Urbana
4          Urbana
48         Urbana
79         Urbana
165        Urbana
            ...
3908024    Urbana
3918192    Urbana
3923578    Urbana
3925210    Urbana
3933541    Urbana
Name: TP_LOCALIZACAO_ESC, Length: 74319, dtype: object

In [ ]:

# Questionário Socioeconômico Q001-Q025
questoes_map = {
    'Q001': {'A': 'Nunca estudou', 'B': 'Não completou 4ª série/5º ano', 
             'C': 'Completou 4ª série/5º ano, mas não 8ª série/9º ano', 
             'D': 'Completou 8ª série/9º ano, mas não Ensino Médio',
             'E': 'Completou Ensino Médio, mas não Faculdade', 
             'F': 'Completou Faculdade, mas não Pós-graduação',
             'G': 'Completou Pós-graduação', 'H': 'Não sei'},
    'Q002': {'A': 'Nunca estudou', 'B': 'Não completou 4ª série/5º ano', 
             'C': 'Completou 4ª série/5º ano, mas não 8ª série/9º ano', 
             'D': 'Completou 8ª série/9º ano, mas não Ensino Médio',
             'E': 'Completou Ensino Médio, mas não Faculdade', 
             'F': 'Completou Faculdade, mas não Pós-graduação',
             'G': 'Completou Pós-graduação', 'H': 'Não sei'},
    'Q003': {'A': 'Grupo 1: Lavrador, agricultor', 'B': 'Grupo 2: Diarista, empregado doméstico',
             'C': 'Grupo 3: Padeiro, cozinheiro, operário', 'D': 'Grupo 4: Professor, técnico, gerente',
             'E': 'Grupo 5: Médico, engenheiro, diretor', 'F': 'Não sei'},
    'Q004': {'A': 'Grupo 1: Lavradora, agricultora', 'B': 'Grupo 2: Diarista, empregada doméstica',
             'C': 'Grupo 3: Padeira, cozinheira, operária', 'D': 'Grupo 4: Professora, técnica, gerente',
             'E': 'Grupo 5: Médica, engenheira, diretora', 'F': 'Não sei'},
    'Q005': {i: str(i) for i in range(1, 21)},
    'Q006': {'A': 'Nenhuma Renda', 'B': 'Até R$ 1.320,00', 'C': 'De R$ 1.320,01 até R$ 1.980,00',
             'D': 'De R$ 1.980,01 até R$ 2.640,00', 'E': 'De R$ 2.640,01 até R$ 3.300,00',
             'F': 'De R$ 3.300,01 até R$ 3.960,00', 'G': 'De R$ 3.960,01 até R$ 5.280,00',
             'H': 'De R$ 5.280,01 até R$ 6.600,00', 'I': 'De R$ 6.600,01 até R$ 7.920,00',
             'J': 'De R$ 7.920,01 até R$ 9.240,00', 'K': 'De R$ 9.240,01 até R$ 10.560,00',
             'L': 'De R$ 10.560,01 até R$ 11.880,00', 'M': 'De R$ 11.880,01 até R$ 13.200,00',
             'N': 'De R$ 13.200,01 até R$ 15.840,00', 'O': 'De R$ 15.840,01 até R$ 19.800,00',
             'P': 'De R$ 19.800,01 até R$ 26.400,00', 'Q': 'Acima de R$ 26.400,00'},
    'Q007': {'A': 'Não', 'B': 'Sim, 1-2 dias/semana', 'C': 'Sim, 3-4 dias/semana', 'D': 'Sim, 5+ dias/semana'},
    'Q008': {'A': 'Não', 'B': 'Sim, um', 'C': 'Sim, dois', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q009': {'A': 'Não', 'B': 'Sim, um', 'C': 'Sim, dois', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q010': {'A': 'Não', 'B': 'Sim, um', 'C': 'Sim, dois', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q011': {'A': 'Não', 'B': 'Sim, uma', 'C': 'Sim, duas', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q012': {'A': 'Não', 'B': 'Sim, uma', 'C': 'Sim, duas', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q013': {'A': 'Não', 'B': 'Sim, uma', 'C': 'Sim, duas', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q014': {'A': 'Não', 'B': 'Sim, uma', 'C': 'Sim, duas', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q015': {'A': 'Não', 'B': 'Sim, uma', 'C': 'Sim, duas', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q016': {'A': 'Não', 'B': 'Sim, um', 'C': 'Sim, dois', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q017': {'A': 'Não', 'B': 'Sim, uma', 'C': 'Sim, duas', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q018': {'A': 'Não', 'B': 'Sim'},
    'Q019': {'A': 'Não', 'B': 'Sim, uma', 'C': 'Sim, duas', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q020': {'A': 'Não', 'B': 'Sim'},
    'Q021': {'A': 'Não', 'B': 'Sim'},
    'Q022': {'A': 'Não', 'B': 'Sim, um', 'C': 'Sim, dois', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q023': {'A': 'Não', 'B': 'Sim'},
    'Q024': {'A': 'Não', 'B': 'Sim, um', 'C': 'Sim, dois', 'D': 'Sim, três', 'E': 'Sim, quatro ou mais'},
    'Q025': {'A': 'Não', 'B': 'Sim'}
}

# Aplicar mapeamento das questões com replace
for coluna, mapa in questoes_map.items():
    df_filter_final[coluna] = df_filter_final[coluna].replace(mapa)

In [ ]:
df_filter_final[questoes_map.keys()]

,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
3,"Completou 8ª série/9º ano, mas não Ensino Médio","Completou 8ª série/9º ano, mas não Ensino Médio","Grupo 2: Diarista, empregado doméstico","Grupo 2: Diarista, empregada doméstica",5,"De R$ 1.320,01 até R$ 1.980,00",Não,"Sim, um","Sim, um",Não,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, três",Não,Não,Sim
4,Não completou 4ª série/5º ano,Não completou 4ª série/5º ano,"Grupo 1: Lavrador, agricultor","Grupo 1: Lavradora, agricultora",4,"Até R$ 1.320,00",Não,"Sim, um",Não,Não,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Não
48,Não sei,"Completou Ensino Médio, mas não Faculdade","Grupo 3: Padeiro, cozinheiro, operário","Grupo 4: Professora, técnica, gerente",5,"Até R$ 1.320,00",Não,Não,"Sim, um",Não,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim
79,"Completou Ensino Médio, mas não Faculdade","Completou Ensino Médio, mas não Faculdade",Não sei,"Grupo 4: Professora, técnica, gerente",2,"Até R$ 1.320,00",Não,"Sim, um","Sim, dois",Não,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim
165,"Completou 8ª série/9º ano, mas não Ensino Médio","Completou 8ª série/9º ano, mas não Ensino Médio","Grupo 2: Diarista, empregado doméstico","Grupo 2: Diarista, empregada doméstica",4,"De R$ 1.320,01 até R$ 1.980,00",Não,"Sim, um","Sim, um",Não,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3908024,"Completou Ensino Médio, mas não Faculdade","Completou Ensino Médio, mas não Faculdade","Grupo 2: Diarista, empregado doméstico","Grupo 2: Diarista, empregada doméstica",3,"Até R$ 1.320,00",Não,"Sim, um","Sim, dois","Sim, um",...,Não,Não,Não,"Sim, duas",Não,Não,"Sim, três",Não,"Sim, um",Sim
3918192,Completou Pós-graduação,Completou Pós-graduação,"Grupo 4: Professor, técnico, gerente","Grupo 4: Professora, técnica, gerente",4,"De R$ 3.960,01 até R$ 5.280,00",Não,"Sim, três","Sim, três","Sim, três",...,"Sim, um",Não,Sim,"Sim, duas",Sim,Sim,"Sim, quatro ou mais",Não,"Sim, quatro ou mais",Sim
3923578,Nunca estudou,Nunca estudou,"Grupo 1: Lavrador, agricultor","Grupo 1: Lavradora, agricultora",1,Nenhuma Renda,Não,Não,Não,Não,...,Não,Não,Não,Não,Não,Não,Não,Não,Não,Não
3925210,"Completou 4ª série/5º ano, mas não 8ª série/9º...","Completou Ensino Médio, mas não Faculdade","Grupo 3: Padeiro, cozinheiro, operário","Grupo 4: Professora, técnica, gerente",4,"De R$ 1.320,01 até R$ 1.980,00",Não,"Sim, um","Sim, dois",Não,...,Não,Não,Não,"Sim, duas",Não,Não,"Sim, quatro ou mais",Sim,"Sim, um",Sim
3933541,"Completou 8ª série/9º ano, mas não Ensino Médio","Completou 4ª série/5º ano, mas não 8ª série/9º...","Grupo 4: Professor, técnico, gerente","Grupo 2: Diarista, empregada doméstica",6,"De R$ 3.960,01 até R$ 5.280,00",Não,"Sim, dois","Sim, quatro ou mais",Não,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, quatro ou mais",Sim,Não,Sim

In [ ]:
# Renomear colunas com base no dicionário
rename_columns = {
    'NU_INSCRICAO': 'Número de Inscrição',
    'NU_ANO': 'Ano do Enem',
    'TP_FAIXA_ETARIA': 'Faixa Etária',
    'TP_SEXO': 'Sexo',
    'TP_ESTADO_CIVIL': 'Estado Civil',
    'TP_COR_RACA': 'Cor/Raça',
    'TP_NACIONALIDADE': 'Nacionalidade',
    'TP_ST_CONCLUSAO': 'Situação de Conclusão do Ensino Médio',
    'TP_ANO_CONCLUIU': 'Ano de Conclusão do Ensino Médio',
    'TP_ESCOLA': 'Tipo de Escola do Ensino Médio',
    'TP_ENSINO': 'Tipo de Instituição de Ensino',
    'IN_TREINEIRO': 'Treineiro',
    'CO_MUNICIPIO_ESC': 'Código do Município da Escola',
    'NO_MUNICIPIO_ESC': 'Nome do Município da Escola',
    'CO_UF_ESC': 'Código da UF da Escola',
    'SG_UF_ESC': 'Sigla da UF da Escola',
    'TP_DEPENDENCIA_ADM_ESC': 'Dependência Administrativa da Escola',
    'TP_LOCALIZACAO_ESC': 'Localização da Escola',
    'TP_SIT_FUNC_ESC': 'Situação de Funcionamento da Escola',
    'CO_MUNICIPIO_PROVA': 'Código do Município da Prova',
    'NO_MUNICIPIO_PROVA': 'Nome do Município da Prova',
    'CO_UF_PROVA': 'Código da UF da Prova',
    'SG_UF_PROVA': 'Sigla da UF da Prova',
    'TP_PRESENCA_CN': 'Presença em Ciências da Natureza',
    'TP_PRESENCA_CH': 'Presença em Ciências Humanas',
    'TP_PRESENCA_LC': 'Presença em Linguagens e Códigos',
    'TP_PRESENCA_MT': 'Presença em Matemática',
    'NU_NOTA_CN': 'Nota Ciências da Natureza',
    'NU_NOTA_CH': 'Nota Ciências Humanas',
    'NU_NOTA_LC': 'Nota Linguagens e Códigos',
    'NU_NOTA_MT': 'Nota Matemática',
    'NU_NOTA_REDACAO': 'Nota Redação',
    'Q001': 'Escolaridade do Pai/Responsável Homem',
    'Q002': 'Escolaridade da Mãe/Responsável Mulher',
    'Q003': 'Ocupação do Pai/Responsável Homem',
    'Q004': 'Ocupação da Mãe/Responsável Mulher',
    'Q005': 'Quantidade de Pessoas na Residência',
    'Q006': 'Renda Mensal Familiar',
    'Q007': 'Empregado Doméstico na Residência',
    'Q008': 'Banheiro na Residência',
    'Q009': 'Quartos para Dormir na Residência',
    'Q010': 'Carro na Residência',
    'Q011': 'Motocicleta na Residência',
    'Q012': 'Geladeira na Residência',
    'Q013': 'Freezer na Residência',
    'Q014': 'Máquina de Lavar Roupa na Residência',
    'Q015': 'Máquina de Secar Roupa na Residência',
    'Q016': 'Forno Micro-ondas na Residência',
    'Q017': 'Máquina de Lavar Louça na Residência',
    'Q018': 'Aspirador de Pó na Residência',
    'Q019': 'Televisão em Cores na Residência',
    'Q020': 'Aparelho de DVD na Residência',
    'Q021': 'TV por Assinatura na Residência',
    'Q022': 'Telefone Celular na Residência',
    'Q023': 'Telefone Fixo na Residência',
    'Q024': 'Computador na Residência',
    'Q025': 'Acesso à Internet na Residência'
}

df_filter_final = df_filter_final.rename(columns=rename_columns)
df_filter_final

,Número de Inscrição,Ano do Enem,Faixa Etária,Sexo,Estado Civil,Cor/Raça,Nacionalidade,Situação de Conclusão do Ensino Médio,Ano de Conclusão do Ensino Médio,Tipo de Escola do Ensino Médio,...,Forno Micro-ondas na Residência,Máquina de Lavar Louça na Residência,Aspirador de Pó na Residência,Televisão em Cores na Residência,Aparelho de DVD na Residência,TV por Assinatura na Residência,Telefone Celular na Residência,Telefone Fixo na Residência,Computador na Residência,Acesso à Internet na Residência
3,210060214087,2023,17 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, três",Não,Não,Sim
4,210059980948,2023,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Não
48,210059388092,2023,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim
79,210060373830,2023,17 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim
165,210060440974,2023,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3908024,210061008506,2023,19 anos,M,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, duas",Não,Não,"Sim, três",Não,"Sim, um",Sim
3918192,210060298399,2023,17 anos,M,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Privada,...,"Sim, um",Não,Sim,"Sim, duas",Sim,Sim,"Sim, quatro ou mais",Não,"Sim, quatro ou mais",Sim
3923578,210061481447,2023,Entre 26 e 30 anos,M,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,Não,Não,Não,Não,Não,Não,Não
3925210,210059173679,2023,24 anos,F,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, duas",Não,Não,"Sim, quatro ou mais",Sim,"Sim, um",Sim
3933541,210060852754,2023,18 anos,M,Solteiro(a),Parda,"Brasileiro(a) Nato(a), nascido(a) no exterior",Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,Não,"Sim, uma",Não,Não,"Sim, quatro ou mais",Sim,Não,Sim

# Merge data

In [ ]:
from geobr import read_municipality

# Baixa dados de todos os municípios brasileiros
municipios = read_municipality(year=2020)
municipios.head()

,code_muni,name_muni,code_state,abbrev_state,name_state,code_region,name_region,geometry
0,1100015.0,Alta Floresta D'oeste,11.0,RO,Rondônia,1.0,Norte,"MULTIPOLYGON (((-62.19465 -11.82746, -62.18945..."
1,1100023.0,Ariquemes,11.0,RO,Rondônia,1.0,Norte,"MULTIPOLYGON (((-62.53648 -9.73222, -62.52765 ..."
2,1100031.0,Cabixi,11.0,RO,Rondônia,1.0,Norte,"MULTIPOLYGON (((-60.37119 -13.36655, -60.37661..."
3,1100049.0,Cacoal,11.0,RO,Rondônia,1.0,Norte,"MULTIPOLYGON (((-61.0008 -11.29737, -61.00103 ..."
4,1100056.0,Cerejeiras,11.0,RO,Rondônia,1.0,Norte,"MULTIPOLYGON (((-61.49976 -13.00525, -61.49426..."

In [ ]:
df_geo = df_filter_final.merge(municipios, left_on='Código do Município da Escola', right_on='code_muni', how='left')
df_geo

,Número de Inscrição,Ano do Enem,Faixa Etária,Sexo,Estado Civil,Cor/Raça,Nacionalidade,Situação de Conclusão do Ensino Médio,Ano de Conclusão do Ensino Médio,Tipo de Escola do Ensino Médio,...,Computador na Residência,Acesso à Internet na Residência,code_muni,name_muni,code_state,abbrev_state,name_state,code_region,name_region,geometry
0,210060214087,2023,17 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Sim,2304400.0,Fortaleza,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -..."
1,210059980948,2023,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,2311306.0,Quixadá,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.95315 -4.66411, -38.9505 -..."
2,210059388092,2023,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Sim,2306405.0,Itapipoca,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-39.54518 -3.08231, -39.53312 ..."
3,210060373830,2023,17 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Sim,2304400.0,Fortaleza,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -..."
4,210060440974,2023,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Sim,2304400.0,Fortaleza,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74314,210061008506,2023,19 anos,M,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,"Sim, um",Sim,2304400.0,Fortaleza,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -..."
74315,210060298399,2023,17 anos,M,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Privada,...,"Sim, quatro ou mais",Sim,2301000.0,Aquiraz,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.40573 -3.82206, -38.40593 ..."
74316,210061481447,2023,Entre 26 e 30 anos,M,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Não,2304400.0,Fortaleza,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -..."
74317,210059173679,2023,24 anos,F,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,...,"Sim, um",Sim,2304400.0,Fortaleza,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -..."
74318,210060852754,2023,18 anos,M,Solteiro(a),Parda,"Brasileiro(a) Nato(a), nascido(a) no exterior",Estou cursando e concluirei em 2023,Não informado,Pública,...,Não,Sim,2307650.0,Maracanaú,23.0,CE,Ceará,2.0,Nordeste,"MULTIPOLYGON (((-38.6379 -3.8014, -38.63773 -3..."

In [ ]:
df_pop = pd.read_excel('POP2024_20241230.xls', skiprows=1, sheet_name='MUNICÍPIOS', dtype={'COD. MUNIC': str})
df_pop = df_pop.loc[df_pop['UF'] == 'CE']
df_pop

      UF  COD. UF COD. MUNIC NOME DO MUNICÍPIO  POPULAÇÃO ESTIMADA Unnamed: 5
891   CE     23.0      00101           Abaiara             10282.0        NaN
892   CE     23.0      00150           Acarape             14306.0        NaN
893   CE     23.0      00200            Acaraú             68758.0        NaN
894   CE     23.0      00309          Acopiara             46215.0        NaN
895   CE     23.0      00408            Aiuaba             14220.0        NaN
...   ..      ...        ...               ...                 ...        ...
1070  CE     23.0      13807       Uruburetama             21279.0        NaN
1071  CE     23.0      13906            Uruoca             14243.0        NaN
1072  CE     23.0      13955           Varjota             18660.0        NaN
1073  CE     23.0      14003     Várzea Alegre             40771.0        NaN
1074  CE     23.0      14102   Viçosa do Ceará             62609.0        NaN

[184 rows x 6 columns]

In [ ]:
df_geo['codigo_cidade'] = df_geo['code_muni'].astype(int).astype(str).str[-5:]
df_geo['codigo_cidade']

0        04400
1        11306
2        06405
3        04400
4        04400
         ...
74314    04400
74315    01000
74316    04400
74317    04400
74318    07650
Name: codigo_cidade, Length: 74319, dtype: object

In [ ]:
df_geo = df_geo.merge(right=df_pop[['COD. MUNIC','POPULAÇÃO ESTIMADA','NOME DO MUNICÍPIO']], how = 'left', left_on = 'codigo_cidade', right_on='COD. MUNIC')
df_geo.drop(columns = ['NOME DO MUNICÍPIO', 'COD. MUNIC'], inplace=True)

In [ ]:
df_geo.drop(columns=['name_state', 'code_region', 'name_region', 'codigo_cidade',
                     'code_muni', 'name_muni', 'code_state', 'abbrev_state',
                     'Número de Inscrição', 'Código da UF da Escola', 'Código do Município da Prova', 'Nome do Município da Prova',
                     'Código da UF da Prova', 'Sigla da UF da Prova'], inplace=True, errors='ignore')
df_geo

,Ano do Enem,Faixa Etária,Sexo,Estado Civil,Cor/Raça,Nacionalidade,Situação de Conclusão do Ensino Médio,Ano de Conclusão do Ensino Médio,Tipo de Escola do Ensino Médio,Tipo de Instituição de Ensino,...,Aspirador de Pó na Residência,Televisão em Cores na Residência,Aparelho de DVD na Residência,TV por Assinatura na Residência,Telefone Celular na Residência,Telefone Fixo na Residência,Computador na Residência,Acesso à Internet na Residência,geometry,POPULAÇÃO ESTIMADA
0,2023,17 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,Ensino Regular,...,Não,"Sim, uma",Não,Não,"Sim, três",Não,Não,Sim,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -...",2574412.0
1,2023,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,Ensino Regular,...,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Não,"MULTIPOLYGON (((-38.95315 -4.66411, -38.9505 -...",88483.0
2,2023,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,Ensino Regular,...,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim,"MULTIPOLYGON (((-39.54518 -3.08231, -39.53312 ...",137892.0
3,2023,17 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,Ensino Regular,...,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -...",2574412.0
4,2023,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,Ensino Regular,...,Não,"Sim, uma",Não,Não,"Sim, um",Não,Não,Sim,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -...",2574412.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74314,2023,19 anos,M,Solteiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,Ensino Regular,...,Não,"Sim, duas",Não,Não,"Sim, três",Não,"Sim, um",Sim,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -...",2574412.0
74315,2023,17 anos,M,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Privada,Ensino Regular,...,Sim,"Sim, duas",Sim,Sim,"Sim, quatro ou mais",Não,"Sim, quatro ou mais",Sim,"MULTIPOLYGON (((-38.40573 -3.82206, -38.40593 ...",84737.0
74316,2023,Entre 26 e 30 anos,M,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,NaN,...,Não,Não,Não,Não,Não,Não,Não,Não,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -...",2574412.0
74317,2023,24 anos,F,Solteiro(a),Branca,Brasileiro(a),Estou cursando e concluirei em 2023,Não informado,Pública,NaN,...,Não,"Sim, duas",Não,Não,"Sim, quatro ou mais",Sim,"Sim, um",Sim,"MULTIPOLYGON (((-38.58413 -3.69368, -38.5814 -...",2574412.0
74318,2023,18 anos,M,Solteiro(a),Parda,"Brasileiro(a) Nato(a), nascido(a) no exterior",Estou cursando e concluirei em 2023,Não informado,Pública,Ensino Regular,...,Não,"Sim, uma",Não,Não,"Sim, quatro ou mais",Sim,Não,Sim,"MULTIPOLYGON (((-38.6379 -3.8014, -38.63773 -3...",249684.0

In [ ]:
df_geo.to_csv('df_all.csv', index=False)

In [ ]:
type(df_geo['geometry'][1])

shapely.geometry.multipolygon.MultiPolygon

In [ ]:
df_filter_final.to_csv('df_enem_2023_ceara.csv', index=False)